### ISSUE TITLE
User model

### ISSUE THREAD

**Issue by amanzanero** [amanzanero/shpe-tutor-scheduler#1]
- [x] add roles: tutor, student (can be both)
- [x] add array of course models to indicate which classes they are currently taking, and have taken in the past
- [x] add array of appointments

**Comment by amanzanero** [comment]
@lealgamb Idk if you have started on this, but I added to the user model bc I started working on the appointments. I will merge to master after I write more tests

**Comment by lealgamb** [comment]
@amanzanero lmk when I can pull so we don't end up with merge conflicts

**Comment by amanzanero** [comment]
@lealgamb I will merge by end of day today

**Comment by amanzanero** [comment]
sorry that it turned out to be today 😅. I just merged so you can jump on it now.
